import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Convex owns this generated surface; its headers intentionally contain
    // broad eslint directives and are regenerated by the Convex CLI.
    "convex/_generated/**",
    // Claude worktrees and reports are shared-agent state, not app sources.
    ".claude/**",
  ]),
]);

export default eslintConfig;
