import type { Author, Course } from "./api";
import type { ForumCategory, ForumPost, ForumTag } from "./forum";

export const courses: Course[] = [
  {
    id: "1",
    title: "מבוא לתכנות",
    description: "קורס מבוא לתכנות בשפת JavaScript",
    image: "/images/courses/intro-to-programming.jpg",
    price: 0,
    duration: 120,
    level: "beginner",
    category: "programming",
    tags: ["javascript", "programming", "web"],
    instructor_id: "1",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    published: true,
    featured: true,
    lessons_count: 10,
    students_count: 100,
    ratings_count: 50,
    average_rating: 4.5,
    instructor: {
      id: "1",
      name: "ד״ר ישראל ישראלי",
      email: "israel@example.com",
      username: "israel_teacher",
      role: "instructor" as const,
      points: 1000,
      level: "מומחה",
      badges: ["מורה מצטיין", "יוצר תוכן"],
      achievements: ["השלמת 100 שיעורים"],
      full_name: "ד״ר ישראל ישראלי",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    lessons: [],
    ratings: [],
    comments: [],
  },
];

export const posts: ForumPost[] = [
  {
    id: "1",
    title: "איך להתחיל ללמוד תכנות?",
    content: "אני רוצה להתחיל ללמוד תכנות, מאיפה כדאי להתחיל?",
    author_id: "1",
    category_id: "1",
    tags: [
      {
        id: "1",
        name: "javascript",
        description: "JavaScript programming language",
        slug: "javascript",
        color: "#f7df1e",
        posts_count: 0,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "2",
        name: "programming",
        description: "General programming topics",
        slug: "programming",
        color: "#3498db",
        posts_count: 0,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "3",
        name: "web",
        description: "Web development",
        slug: "web",
        color: "#2ecc71",
        posts_count: 0,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
    ],
    pinned: false,
    solved: false,
    likes: 10,
    views: 100,
    last_activity: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    author: {
      id: "2",
      name: "יוסי כהן",
      email: "yossi@example.com",
      username: "yossi123",
      role: "user" as const,
      points: 150,
      level: "מתחיל",
      badges: ["משתתף פעיל"],
      achievements: ["פרסום 10 פוסטים"],
      full_name: "יוסי כהן",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    category: {
      id: "1",
      name: "כללי",
      description: "דיונים כלליים",
      slug: "general",
      order: 1,
      icon: "MessageSquare",
      color: "#3498db",
      posts_count: 0,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
];

export const users: Author[] = [
  {
    id: "1",
    name: "ישראל ישראלי",
    email: "israel@example.com",
    username: "israel",
    role: "user",
    points: 100,
    level: "מתחיל",
    badges: ["משתתף פעיל"],
    achievements: ["10 פוסטים"],
    full_name: "ישראל ישראלי",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
