import { Course } from "@/types/courses"

export const EXAMPLE_COURSES: Course[] = [
  {
    id: "1",
    title: "יסודות התקשורת הזוגית",
    description: "למדו את היסודות החשובים ביותר לתקשורת בריאה ואפקטיבית בזוגיות",
    thumbnail: "/images/courses/communication.jpg",
    duration: 120,
    level: "beginner",
    lessons: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    authorId: "1",
    published: true,
    price: 199,
    rating: 4.8,
    studentsCount: 120,
    tags: ["תקשורת", "זוגיות", "מתחילים"],
  },
  {
    id: "2",
    title: "בניית אינטימיות ואמון",
    description: "גלו כיצד לבנות ולחזק את האינטימיות והאמון במערכת היחסים שלכם",
    thumbnail: "/images/courses/intimacy.jpg",
    duration: 180,
    level: "intermediate",
    lessons: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    authorId: "1",
    published: true,
    price: 249,
    rating: 4.9,
    studentsCount: 85,
    tags: ["אינטימיות", "אמון", "זוגיות"],
  },
  {
    id: "3",
    title: "התמודדות עם קונפליקטים",
    description: "למדו טכניקות מעשיות לפתרון קונפליקטים ומחלוקות בזוגיות",
    thumbnail: "/images/courses/conflicts.jpg",
    duration: 150,
    level: "advanced",
    lessons: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    authorId: "1",
    published: true,
    price: 299,
    rating: 4.7,
    studentsCount: 65,
    tags: ["קונפליקטים", "תקשורת", "מתקדמים"],
  },
] 