import { Course } from "@/types/api";

export const courses: Course[] = [
  {
    id: "1",
    title: "מבוא לתכנות בג'אווהסקריפט",
    description: "למד את יסודות התכנות בשפת ג'אווהסקריפט",
    author: {
      id: "1",
      name: "ישראל ישראלי",
      email: "israel@example.com",
      avatar_url: null,
      bio: "מדריך תכנות מנוסה",
      created_at: "2024-01-01T00:00:00Z",
      updated_at: "2024-01-01T00:00:00Z",
    },
    price: 0,
    rating: 4.5,
    ratings_count: 120,
    students_count: 500,
    lessons_count: 10,
    duration: 600,
    level: "beginner",
    tags: ["javascript", "programming", "web"],
    thumbnail_url: "/images/courses/javascript.jpg",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
    status: "published",
    image_url: "/images/courses/javascript.jpg",
    author_id: "1",
    ratings: [],
    sections: [],
    lessons: [],
    instructor: {
      id: "1",
      name: "ישראל ישראלי",
      email: "israel@example.com",
      avatar_url: null,
      bio: "מדריך תכנות מנוסה",
    },
  },
  {
    id: "2",
    title: "פיתוח אפליקציות React",
    description: "למד לבנות אפליקציות מודרניות עם React",
    author: {
      id: "2",
      name: "יעקב יעקובי",
      email: "yaakov@example.com",
      avatar_url: null,
      bio: "מפתח React בכיר",
      created_at: "2024-01-01T00:00:00Z",
      updated_at: "2024-01-01T00:00:00Z",
    },
    price: 199,
    rating: 4.8,
    ratings_count: 80,
    students_count: 300,
    lessons_count: 15,
    duration: 900,
    level: "intermediate",
    tags: ["react", "javascript", "web"],
    thumbnail_url: "/images/courses/react.jpg",
    created_at: "2024-01-02T00:00:00Z",
    updated_at: "2024-01-02T00:00:00Z",
    status: "published",
    image_url: "/images/courses/react.jpg",
    author_id: "2",
    ratings: [],
    sections: [],
    lessons: [],
    instructor: {
      id: "2",
      name: "יעקב יעקובי",
      email: "yaakov@example.com",
      avatar_url: null,
      bio: "מפתח React בכיר",
    },
  },
  {
    id: "3",
    title: "Node.js למתקדמים",
    description: "למד לבנות שרתים מתקדמים עם Node.js",
    author: {
      id: "3",
      name: "דוד דוידי",
      email: "david@example.com",
      avatar_url: null,
      bio: "מומחה Node.js",
      created_at: "2024-01-01T00:00:00Z",
      updated_at: "2024-01-01T00:00:00Z",
    },
    price: 299,
    rating: 4.9,
    ratings_count: 50,
    students_count: 200,
    lessons_count: 20,
    duration: 1200,
    level: "advanced",
    tags: ["nodejs", "javascript", "backend"],
    thumbnail_url: "/images/courses/nodejs.jpg",
    created_at: "2024-01-03T00:00:00Z",
    updated_at: "2024-01-03T00:00:00Z",
    status: "draft",
    image_url: "/images/courses/nodejs.jpg",
    author_id: "3",
    ratings: [],
    sections: [],
    lessons: [],
    instructor: {
      id: "3",
      name: "דוד דוידי",
      email: "david@example.com",
      avatar_url: null,
      bio: "מומחה Node.js",
    },
  },
];
