import { ExtendedForumPost, ForumCategory } from "@/types/forum";

export const MOCK_POSTS: ExtendedForumPost[] = [
  {
    id: "1",
    title: "איך להתחיל ללמוד תכנות?",
    content:
      "אני רוצה להתחיל ללמוד תכנות אבל אני לא יודע מאיפה להתחיל. יש לכם המלצות?",
    author: {
      id: "1",
      name: "ישראל ישראלי",
      username: "israel123",
      full_name: "ישראל ישראלי",
      email: "israel@example.com",
      avatar_url: "/avatars/user1.jpg",
      bio: "מפתח Full Stack עם ניסיון של 5 שנים",
      role: "user",
      image: null,
      created_at: "2024-01-01T00:00:00Z",
      updated_at: "2024-01-01T00:00:00Z",
      last_seen: "2024-01-15T12:00:00Z",
      points: 1000,
      level: 5,
      badges: ["מפתח מצטיין", "תורם פעיל"],
      achievements: ["השלים 10 קורסים", "פתר 100 תרגילים"],
    },
    author_id: "1",
    created_at: "2024-01-01T10:00:00Z",
    updated_at: "2024-01-01T10:00:00Z",
    comments: [],
    likes: 0,
    views: 0,
    tags: ["תכנות", "התחלה"],
    category: "general",
    isLiked: false,
    isBookmarked: false,
    replies_count: 0,
    last_activity: "2024-01-01T10:00:00Z",
    last_reply: null,
    pinned: false,
    solved: false,
  },
  {
    id: "2",
    title: "המלצות לקורסים מתקדמים",
    content:
      "אני מחפש המלצות לקורסים מתקדמים בפיתוח ווב. אשמח לשמוע על הניסיון שלכם.",
    author: {
      id: "2",
      name: "שרה כהן",
      username: "dana_c",
      full_name: "דנה כהן",
      email: "sarah@example.com",
      avatar_url: "/avatars/user2.jpg",
      bio: "סטודנטית למדעי המחשב",
      role: "user",
      image: null,
      created_at: "2024-01-02T00:00:00Z",
      updated_at: "2024-01-02T00:00:00Z",
      last_seen: "2024-01-14T15:30:00Z",
      points: 750,
      level: 3,
      badges: ["מתחילה מבטיחה"],
      achievements: ["השלים 5 קורסים"],
    },
    author_id: "2",
    created_at: "2024-01-02T15:30:00Z",
    updated_at: "2024-01-02T15:30:00Z",
    comments: [],
    likes: 0,
    views: 0,
    tags: ["קורסים", "פיתוח ווב"],
    category: "general",
    isLiked: false,
    isBookmarked: false,
    replies_count: 0,
    last_activity: "2024-01-02T15:30:00Z",
    last_reply: null,
    pinned: false,
    solved: false,
  },
  {
    id: "3",
    title: "טיפים לראיון עבודה",
    content:
      "יש לי ראיון עבודה בשבוע הבא לתפקיד מפתח פרונטאנד. אשמח לטיפים והמלצות.",
    author: {
      id: "3",
      name: "יוסף לוי",
      username: "yossi_l",
      full_name: "יוסי לוי",
      email: "yosef@example.com",
      avatar_url: "/avatars/user3.jpg",
      bio: "מפתח React מנוסה",
      role: "user",
      image: null,
      created_at: "2024-01-03T00:00:00Z",
      updated_at: "2024-01-03T00:00:00Z",
      last_seen: "2024-01-15T09:45:00Z",
      points: 1200,
      level: 6,
      badges: ["מומחה React", "מנטור"],
      achievements: ["השלים 15 קורסים", "פתר 200 תרגילים"],
    },
    author_id: "3",
    created_at: "2024-01-03T09:15:00Z",
    updated_at: "2024-01-03T09:15:00Z",
    comments: [],
    likes: 0,
    views: 0,
    tags: ["קריירה", "ראיונות עבודה"],
    category: "general",
    isLiked: false,
    isBookmarked: false,
    replies_count: 0,
    last_activity: "2024-01-03T09:15:00Z",
    last_reply: null,
    pinned: false,
    solved: false,
  },
];

export const FORUM_CATEGORIES: ForumCategory[] = [
  {
    id: "1",
    name: "כללי",
    description: "דיונים כלליים בנושאי תכנות ופיתוח",
    slug: "general",
    order: 1,
    icon: "🌟",
    posts_count: 156,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "2",
    name: "שאלות טכניות",
    description: "שאלות ספציפיות בנושאים טכניים",
    slug: "technical",
    order: 2,
    icon: "❓",
    posts_count: 98,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "3",
    name: "קריירה",
    description: "דיונים בנושאי קריירה, משרות וראיונות עבודה",
    slug: "career",
    order: 3,
    icon: "💼",
    posts_count: 124,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
];
