import { mockAuthor, mockCategory, mockTag } from "./forum";
import { MOCK_USERS } from "./users";
import type {
  ExtendedForumPost,
  ForumPost,
} from "@/types/forum";



export const SAMPLE_POSTS: ExtendedForumPost[] = [
  {
    id: "1",
    title: "איך להתחיל ללמוד תכנות?",
    content: "אני רוצה להתחיל ללמוד תכנות אבל לא יודע מאיפה להתחיל...",
    author_id: "1",
    category_id: "1",
    author: {
      id: "1",
      name: "משתמש חדש",
      image: undefined,
      role: "user" as const,
      bio: "מתכנת מתחיל",
      username: "newbie",
      email: "user@example.com",
      avatar_url: undefined,
      points: 0,
      level: 1,
      badges: [],
      achievements: [],
      full_name: "משתמש חדש",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      last_seen: undefined,
    },
    category: {
      id: "1",
      name: "שאלות כלליות",
      description: "שאלות כלליות בנושא תכנות",
      slug: "general-questions",
      order: 1,
      icon: "question-mark",
      color: "blue",
      posts_count: 0,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    tags: [
      {
        id: "1",
        name: "תכנות",
        description: "שאלות בנושא תכנות",
        slug: "programming",
        color: "blue",
        posts_count: 0,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "2",
        name: "התחלה",
        description: "שאלות למתחילים",
        slug: "beginners",
        color: "green",
        posts_count: 0,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
    ],
    pinned: false,
    solved: false,
    likes: 0,
    views: 10,
    comments_count: 0,
    last_activity: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "2",
    title: "המלצות ללימוד React",
    content: "אשמח להמלצות על קורסים ומשאבים ללימוד React...",
    author_id: "2",
    category_id: "2",
    author: {
      id: "2",
      name: "מדריך",
      image: undefined,
      role: "instructor" as const,
      bio: "מדריך בכיר",
      username: "instructor",
      email: "instructor@example.com",
      avatar_url: undefined,
      points: 500,
      level: 5,
      badges: [],
      achievements: [],
      full_name: "מדריך",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      last_seen: undefined,
    },
    category: {
      id: "2",
      name: "React",
      description: "שאלות ודיונים בנושא React",
      slug: "react",
      order: 2,
      icon: "react",
      color: "blue",
      posts_count: 0,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    tags: [
      {
        id: "3",
        name: "React",
        description: "שאלות בנושא React",
        slug: "react",
        color: "blue",
        posts_count: 0,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "4",
        name: "JavaScript",
        description: "שאלות בנושא JavaScript",
        slug: "javascript",
        color: "yellow",
        posts_count: 0,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
    ],
    pinned: true,
    solved: false,
    likes: 5,
    views: 100,
    comments_count: 2,
    last_activity: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const mockPost: ExtendedForumPost = {
  id: "1",
  title: "איך להתחיל ללמוד תכנות?",
  content:
    "אני רוצה להתחיל ללמוד תכנות אבל לא יודע מאיפה להתחיל. מה אתם ממליצים?",
  author_id: "1",
  category_id: "1",
  category: {
    id: "1",
    name: "שאלות ותשובות",
    description: "שאלות טכניות ועזרה הדדית",
    slug: "questions",
    order: 1,
    icon: "HelpCircle",
    color: "#2ecc71",
    posts_count: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  tags: [
    {
      id: "1",
      name: "התחלה",
      description: "שאלות למתחילים",
      slug: "beginners",
      color: "#3498db",
      posts_count: 0,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: "2",
      name: "המלצות",
      description: "המלצות ועצות",
      slug: "recommendations",
      color: "#2ecc71",
      posts_count: 0,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ],
  pinned: false,
  solved: false,
  likes: 5,
  views: 100,
  last_activity: new Date().toISOString(),
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
  comments: [],
  author: {
    id: "1",
    name: "ישראל ישראלי",
    email: "israel@example.com",
    username: "israel",
    role: "user" as const,
    points: 100,
    level: 1,
    badges: ["משתתף פעיל"],
    achievements: ["10 פוסטים"],
    full_name: "ישראל ישראלי",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
};

export const mockPost2: ExtendedForumPost = {
  id: "2",
  title: "טיפים ללימוד React",
  content: "אשמח לקבל טיפים ללימוד React בצורה יעילה",
  author_id: "2",
  category_id: "2",
  category: {
    id: "2",
    name: "שאלות ותשובות",
    description: "שאלות טכניות ועזרה הדדית",
    slug: "questions",
    order: 2,
    icon: "HelpCircle",
    color: "#2ecc71",
    posts_count: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  tags: [
    {
      id: "3",
      name: "React",
      description: "React Framework",
      slug: "react",
      color: "#61dafb",
      posts_count: 0,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: "4",
      name: "לימוד",
      description: "חומרי לימוד",
      slug: "learning",
      color: "#e74c3c",
      posts_count: 0,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ],
  pinned: false,
  solved: false,
  likes: 3,
  views: 50,
  last_activity: new Date().toISOString(),
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
  comments: [],
  author: {
    id: "2",
    name: "יוסי כהן",
    email: "yossi@example.com",
    username: "yossi",
    role: "user" as const,
    points: 50,
    level: 1,
    badges: ["משתתף חדש"],
    achievements: ["5 פוסטים"],
    full_name: "יוסי כהן",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
};

export const posts: ForumPost[] = [
  {
    id: "1",
    title: "איך להתחיל ללמוד תכנות?",
    content: "אני רוצה להתחיל ללמוד תכנות, מאיפה כדאי להתחיל?",
    author_id: mockAuthor.id,
    category_id: mockCategory.id,
    category: mockCategory,
    tags: [mockTag],
    pinned: false,
    solved: false,
    likes: 10,
    views: 100,
    last_activity: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    author: mockAuthor,
    comments: [],
    comments_count: 0,
  },
];
