import type { User } from "@/types/api";

export const users: User[] = [
  {
    id: "1",
    email: "john@example.com",
    name: "John Doe",
    full_name: "John Doe",
    username: "johndoe",
    avatar_url: "/images/avatars/john.jpg",
    image: "/images/avatars/john.jpg",
    bio: "מורה ותיק לפיזיקה",
    role: "instructor",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
    last_seen: "2024-03-14T12:00:00Z",
    points: 1000,
    level: 5,
    badges: ["מורה מצטיין", "מנטור"],
    achievements: ["first_course", "expert_teacher"],
    is_online: true,
    settings: {
      notifications: true,
      theme: "light",
      language: "he",
    },
  },
  {
    id: "2",
    email: "jane@example.com",
    name: "Jane Smith",
    full_name: "Jane Smith",
    username: "janesmith",
    avatar_url: "/images/avatars/jane.jpg",
    image: "/images/avatars/jane.jpg",
    bio: "מורה למתמטיקה ומדריכה פדגוגית",
    role: "instructor",
    created_at: "2024-01-02T00:00:00Z",
    updated_at: "2024-01-02T00:00:00Z",
    last_seen: "2024-03-14T11:30:00Z",
    points: 750,
    level: 3,
    badges: ["מורה מצטיינת"],
    achievements: ["master_teacher", "community_leader"],
    is_online: false,
    settings: {
      notifications: true,
      theme: "dark",
      language: "he",
    },
  },
  {
    id: "3",
    email: "admin@example.com",
    name: "Admin User",
    full_name: "Admin User",
    username: "admin",
    avatar_url: "/images/avatars/admin.jpg",
    image: "/images/avatars/admin.jpg",
    bio: "מנהל המערכת",
    role: "admin",
    created_at: "2024-01-03T00:00:00Z",
    updated_at: "2024-01-03T00:00:00Z",
    last_seen: "2024-03-14T12:30:00Z",
    points: 1500,
    level: 10,
    badges: ["מנהל ראשי"],
    achievements: ["system_master"],
    is_online: true,
    settings: {
      notifications: true,
      theme: "system",
      language: "he",
    },
  },
];
