name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    env:
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linting
      run: npm run lint
    
    - name: Run type checking
      run: npm run type-check
    
    - name: Run unit and integration tests
      run: npm run test
    
    - name: Run E2E tests
      run: |
        npx playwright install --with-deps
        npm run test:e2e
    
    - name: Run accessibility tests
      run: npm run test:a11y
    
    - name: Upload test coverage
      uses: actions/upload-artifact@v4
      with:
        name: coverage
        path: coverage/
    
    - name: Check test coverage
      run: |
        COVERAGE=$(npm run test:coverage | grep "All files" | awk '{print $4}' | tr -d '%')
        if [ "$COVERAGE" -lt 80 ]; then
          echo "Test coverage is below 80%"
          exit 1
        fi

  build:
    name: Build Check
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build project
      run: npm run build 